### ISSUE TITLE
still lots of warnings from mockery

### ISSUE THREAD

**Issue by epinault** [appunite/mockery#42]
using OTP. 27.1.1 and Elixir 1.17.3 , we are getting tons of warnings still despite the changelog in 2.3.3

 warning: Mockery.Proxy.MacroProxy.stream/1 is undefined or private
    │
 36 │       |> mockable(RemoteCSV).stream()
    │                              ~
    │

because we use warning as errors, it s blocking us to upgrade

**Comment by amatalai** [comment]
Hi @epinault 
Did you replace `import Mockery.Macro` with `use Mockery.Macro` after upgrading to 2.3.3?

**Comment by epinault** [comment]
@amatalai  let me check. Maybe I might have missed some spot.

**Comment by epinault** [comment]
looks like it works. Thank you!
